### ISSUE TITLE
sqldf coercion error when variable with column name exists

### ISSUE THREAD

**Issue by tomastelensky** [ggrothendieck/sqldf#23]
I found a strange behaviour of sqldf - it issues "NAs introduced by coercion" warning when a variable exists with the same name as a column and different data type. The following code:

```R
x <- structure(list(euring = c(12380, 12430), species = c("Locustella luscinioides", 
"Acrocephalus schoenobaenus")), .Names = c("euring", "species"
), row.names = 1:2, class = "data.frame")

species <- structure(list(EURING = c(0, 980), Species = c(NA_integer_, NA_integer_
)), .Names = c("EURING", "Species"), row.names = 1:2, class = "data.frame")

require(sqldf)

result <- sqldf("
select species as Species
from x
")
```

produces:

```
Warning message: In FUN(X[[i]], ...) : NAs introduced by coercion
```

and result then contains only NAs.

If variable `species` didn't exist, everything is OK. But sqldf shoudln't even touch the variable `species`, right??

**Comment by JARDnc** [comment]
When `method = NULL`, in the last part of the function, the `auto` function that replaces the query with the erroneous object is applied, because the `Species` column is found.

```
> dfnames
[1] "species" "df"     
> tab
     dfname                            
[1,] "species" "EURING"  "numeric"   ""
[2,] "species" "Species" "integer"   ""
[3,] "df"      "euring"  "numeric"   ""
[4,] "df"      "species" "character" ""
> cn
[1] "Species"
```

**Comment by ggrothendieck** [comment]
Yes, that is how the heuristic works.  It looks for a column of the same name and tries to convert the column that its class.  Such a heuristic is needed because SQLite does not support all the classes that R does.

If you want to avoid the use of the heuristic then use `sqldf(..., method = "raw")` or specify the classes yourself (see `?sqldf` method argument for more info) or use a different backend e.g. library(RH2); sqldf(...)` .
