### ISSUE TITLE
Row names not set by read.csv.sql()

### ISSUE THREAD

**Issue by owenjonesuob** [ggrothendieck/sqldf#27]
### Problem

According to the documentation for `sqldf::read.csv.sql()`, the `row.names` parameter should behave identically to `read.csv()`. However, it seems to have no effect.

---

### System info

**OS:** Windows, RHEL6/7
**R:** 3.4.3
**sqldf:** 0.4-11

---

#### `data.csv`
```
"name", "value"
"one", 1
"two", 2
"three", 3
```

#### `example.R`
``` r
# No rownames, first column is $name
read.csv("data.csv")

# Rownames are set to values from "name" column in file
read.csv("data.csv", row.names = "name")


# Both produce the same output (no rownames, first column is $name)
read.csv.sql("data.csv")
read.csv.sql("data.csv", row.names = "name")
```

**Comment by ggrothendieck** [comment]
The documentation for `row.names` in `?sqldf` does not say that it behaves identically to the that argument of `read.csv`.  What it does say is:

> For TRUE the tables in the data base are given a row_names column filled with the row names of the 
> corresponding data frames. Note that in SQLite a special rowid (or equivalently oid or _rowid_) is 
> available in any case.

**Comment by owenjonesuob** [comment]
Thanks for the quick response!

Considering your explanation above, perhaps the documentation for`row.names` in `read.csv.sql()` should point users towards `sqldf()`, rather than `read.csv()`?

Having said that, I am still struggling to see how `row.names` should be used in `read.csv.sql()`. Would you possibly be able to provide an example?

#### `data.csv`

```
"row_names", "value"
"one", 1
"two", 2
"three", 3
```

#### `example.R`

``` r
# "row_names" column is dropped either way
read.csv.sql("test.csv", row.names = FALSE)
read.csv.sql("test.csv", row.names = TRUE)

##   value
## 1     1
## 2     2
## 3     3
```

**Comment by ggrothendieck** [comment]
Sorry. I see where it refers to read.csv now in ?read.sql.csv.   Seems to be a bug.

If you want to read it in you can do this on Windows if you have Rtools on your path.  You may need to modify the filter statement slightly depending on your shell if you are not on Windows.  The filter argument is needed in order to remove the quotes as they are not supported by sqlite's reader which is fairly basic.
```
DF <- read.csv.sql("data.csv", method = "raw", filter = 'tr.exe -d \'^"\' ')
rownames(DF) <- DF$row_names
DF <- DF[-1]
```
Alternately change the name of the row_names column in the file to something else prior to reading it in in which case you won't need method = "raw".
