### ISSUE TITLE
Issue warning on date operations

### ISSUE THREAD

**Issue by lindeloev** [ggrothendieck/sqldf#54]
Per the documentation, `sqldf` silently converts dates and POSIXct to linux timestamps. It would save new users a lot of debugging time if an informative message/warning was issued when `sqldf` imports data with Date/POSIXct columns. Perhaps like {tidyverse} where a waning is issued every 8 hours or so.

Here is a simple filtering on dates and the expected result:

```r
df_dates = data.frame(x = as.Date(c("2022-01-01", "2023-01-01", "2024-01-01", "2025-01-01")))
df_dates[df_dates$x < "2023-06-29", ]
```
> [1] "2022-01-01" "2023-01-01"

Doing the equivalent in `sqldf` gives surprising results if you don't know that you're really comparing to a linux timestamp:
```r
sqldf::sqldf("SELECT * FROM df_dates WHERE x < '2023-06-29'")
sqldf::sqldf("SELECT * FROM df_dates WHERE x < CURRENT_TIMESTAMP")
sqldf::sqldf("SELECT * FROM df_dates WHERE x < DATE('now')")
sqldf::sqldf("SELECT * FROM df_dates WHERE CAST(x AS DATE) < DATE('now')")
sqldf::sqldf("SELECT * FROM df_dates WHERE DATE(x) < DATE('now')")
sqldf::sqldf("SELECT * FROM df_dates WHERE strftime('%Y-%m-%d', x) < '2023-06-29'")
sqldf::sqldf("SELECT * FROM df_dates WHERE DATE(x) < DATE('2023-06-29')")
```
> 2022-01-01
> 2023-01-01
> 2024-01-01
> 2025-01-01

Also surprising:
```r
sqldf::sqldf("SELECT * FROM df_dates WHERE x < CAST('2023-06-29' AS DATE)")
sqldf::sqldf("SELECT * FROM df_dates WHERE CAST(x AS DATE) < CAST('2023-06-29' AS DATE)")
```
> <0 rows> (or 0-length row.names)

```

**Comment by ggrothendieck** [comment]
SQLite does not have a date type so SQLite gets the R internal representation of R Date class which is the number of days since the UNIX Epoch -- not a timestamp.  For POSIXct objects it gets the internal representation which is the number of seconds since the UNIX Epoch.  All the other backends to sqldf do support a date type and Date class objects get converted appropriately.  Read sqldf FAQ #4 on the sqldf github site for more info.  https://github.com/ggrothendieck/sqldf
